	SUBROUTINE RANGE(NSQ,XLAMIN,XLAMAX,XLAMID,XLOMIN,XLOMAX,XLOMID,
     &	nsqrs,nsqtot,nlatzones,n,eq_incr)
C
C FINDS THE COORDINATE RANGE OF SQUARE NUMBER 'NSQ'
C
	DIMENSION NSQRS(NLATZONES),NSQTOT(NLATZONES)
C
	LAZONE=2
	DO WHILE (NSQ.GT.NSQTOT(LAZONE))
	   LAZONE=LAZONE+1
	ENDDO
	LAZONE=LAZONE-1
	NNSQ=NSQ-NSQTOT(LAZONE)
	XLAMIN=90.-LAZONE*eq_incr
	XLAMAX=XLAMIN+eq_incr
	XLAMID=XLAMIN+(eq_incr*0.5)
	GRSIZE=360./NSQRS(LAZONE)
	XLOMAX=NNSQ*GRSIZE
	XLOMIN=XLOMAX-GRSIZE
	XLOMID=XLOMAX-(GRSIZE*0.5)
	RETURN
	END
