

      SUBROUTINE DELAZ(EPLAT,EPLONG,STLAT,STLONG,DELTA,AZEP,AZST)
      DATA GEOCO,HPI,TWOPI,RAD,REPRAD/.993277,1.5707963,
     16.2831853,.0174533,57.29578/
      TAN(X)=SIN(X)/COS(X)
      ARCOS(X)=ATAN2(SQRT(1.-X*X),X)
      EL=ATAN(GEOCO*TAN(EPLAT*RAD))
      EL=HPI-EL
      STL=ATAN(GEOCO*TAN(STLAT*RAD))
      STL=HPI-STL
      ELON=EPLONG*RAD
      SLON=STLONG*RAD
      AS=COS(STL)
      BS=SIN(STL)
      CS=COS(SLON)
      DS=SIN(SLON)
      A=COS(EL)
      B=SIN(EL)
      C=COS(ELON)
      D=SIN(ELON)
      CDEL=A*AS+B*BS*(C*CS+D*DS)
      IF(ABS(CDEL).GT.1.) CDEL=SIGN(1.,CDEL)
      DELT=ARCOS(CDEL)
      DELTA=DELT*REPRAD
      SDEL=SIN(DELT)
      CAZE=(AS-A*CDEL)/(SDEL*B)
      IF(ABS(CAZE).GT.1.) CAZE=SIGN(1.,CAZE)
      AZE=ARCOS(CAZE)
      IF(BS.GT.0.) CAZS=(A-AS*CDEL)/(BS*SDEL)
      IF(BS.EQ.0.) CAZS=SIGN(1.,CAZS)
      IF(ABS(CAZS).GT.1.) CAZS=SIGN(1.,CAZS)
      AZS=ARCOS(CAZS)
      DIF=DS*C-CS*D
      IF(DIF.LT.0.) AZE=TWOPI-AZE
      AZEP=REPRAD*AZE
      IF(DIF.GT.0.) AZS=TWOPI-AZS
      AZST=REPRAD*AZS
      RETURN
      END
