
C      SUBROUTINE MATINV
C$PROG MATINV
      SUBROUTINE MATINV(A,N,M,DET)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION A,DET
C     THIS SUBROUTINE IS FOR MATRIX INVERSION AND SIMULT. LINEAR EQS.
C     A = THE GIVEN COEFFICIENT MATRIX A; A-1 WILL BE STORED IN THIS MAT
C         -RIX AT RETURN TO THE MAIN PROGRAM
C     N = ORDER OF A, N > OR = 1.
C     M = DIMENSION OF A IN THE CALLING PROGRAM
C     DET = VALUE OF DETERMINANT
      DIMENSION A(M,M),IPVOT(40),INDEX(40,2),PIVOT(40)
      EQUIVALENCE (IROW,JROW),(ICOL,JCOL)
C     FOLLOWING 3 STATMENTS FOR INITIALIZATION
      DET=1.D0
      DO 17 J=1,N
   17 IPVOT(J)=0
      DO 135 I=1,N
C     FOLLOWING 12 STATEMENTS FOR SEARCH FOR PIVOT ELEMENT
      T=0.D0
      DO 9 J=1,N
      IF(IPVOT(J)-1)13,9,13
   13 DO 23 K=1,N
      IF(IPVOT(K)-1)43,23,81
   43 IF(DDABS(T)-DDABS(A(J,K)))83,23,23
   83 IROW=J
      ICOL=K
      T=A(J,K)
   23 CONTINUE
    9 CONTINUE
      IPVOT(ICOL)=IPVOT(ICOL)+1
C     FOLLOWING 15 STATEMENTS TO PUT PIVOT ELEMENT ON DIAGONAL
      IF(IROW-ICOL)73,109,73
   73 DET=-DET
      DO 12 L=1,N
      T=A(IROW,L)
      A(IROW,L)=A(ICOL,L)
   12 A(ICOL,L)=T
  109 INDEX(I,1)=IROW
      INDEX(I,2)=ICOL
      PIVOT(I)=A(ICOL,ICOL)
      DET=DET*PIVOT(I)
C     FOLLOWING 6 STATEMENTS TO DIVIDE PIVOT ROW BY PIVOT ELEMENT
      A(ICOL,ICOL)=1.D0
      DO 205 L=1,N
  205 A(ICOL,L)=A(ICOL,L)/PIVOT(I)
C      FOLLOWING 10 STATEMENTS TO REDUCE NON-PIVOT ROWS
      DO 135 LI=1,N
      IF(LI-ICOL)21,135,21
   21 T=A(LI,ICOL)
      A(LI,ICOL)=0.D0
      DO 89 L=1,N
   89 A(LI,L)=A(LI,L)-A(ICOL,L)*T
  135 CONTINUE
C     FOLLOWING 11 STATEMENTS TO INTERCHANGE COLUMNS
      DO 3 I=1,N
      L=N-I+1
      IF(INDEX(L,1)-INDEX(L,2))19,3,19
   19 JROW=INDEX(L,1)
      JCOL=INDEX(L,2)
      DO 549 K=1,N
      T=A(K,JROW)
      A(K,JROW)=A(K,JCOL)
      A(K,JCOL)=T
  549 CONTINUE
    3 CONTINUE
   81 RETURN
      END
