C$PROG REMAVL
C$XREF
      SUBROUTINE REMAVL(N,DATA)
      DOUBLE PRECISION DET,SUMX,SUMX2,SUMY,SUMXY,A,B
      DIMENSION DATA(1)
      SUMX=DFLOAT(N)*DFLOAT(N+1)*0.5D0
      SUMX2=SUMX*DFLOAT(2*N+1)/3.D0
      SUMY=0.D0
      SUMXY=0.D0
      DO 1 I=1,N
      SUMY=SUMY+DBLE(DATA(I))
    1 SUMXY=SUMXY+DFLOAT(I)*DBLE(DATA(I))
      DET=DFLOAT(N)*SUMX2-SUMX*SUMX
      IF(DET.NE.0) THEN
        A=(DFLOAT(N)*SUMXY-SUMX*SUMY)/DET
        BB=(SUMX2*SUMY-SUMXY*SUMX)/DET
      ELSE
        A=0.
        BB=0.
      ENDIF
      DO 2 I=1,N
    2 DATA(I)=DATA(I)-DFLOAT(I)*A-BB
      RETURN
      END
